name: Check packages with clang-format

on: [pull_request_target]

permissions:
  contents: read
  pull-requests: write

jobs:
  clang_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: "${{ github.event.pull_request.head.sha }}"

    - uses: DoozyX/clang-format-lint-action@bcb4eb2cb0d707ee4f3e5cc3b456eb075f12cf73 # v0.20
      with:
        source: './packages/galeri/src-xpetra ./packages/galeri/example-tpetra ./packages/galeri/example-xpetra ./packages/galeri/test ./packages/ifpack2 ./packages/muelu ./packages/tempus ./packages/teko ./packages/xpetra'
        exclude: './packages/tempus/examples'
        extensions: 'cpp,hpp'
        clangFormatVersion: 14
        inplace: true
    - run: git diff HEAD > format_patch.txt
    - run: if [ "$(cat format_patch.txt)" == "" ] ; then rm format_patch.txt ; else cat format_patch.txt; fi

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      id: upload-artf
      if: ${{ hashFiles('format_patch.txt') != '' }}
      with:
        name: clang format patch
        path: format_patch.txt

    - if: ${{ hashFiles('format_patch.txt') != '' }}
      run: |
        echo "Your PR updated files that did not respect package clang formatting settings." >> format_patch_message.txt
        echo "Please apply the patch given below. Alternatively you can download a patch file [here](${{ steps.upload-artf.outputs.artifact-url }})." >> format_patch_message.txt
        echo "<details>" >> format_patch_message.txt
        echo "<summary>Patch</summary>" >> format_patch_message.txt
        echo "" >> format_patch_message.txt
        echo "\`\`\`diff" >> format_patch_message.txt
        cat format_patch.txt >> format_patch_message.txt
        echo "\`\`\`" >> format_patch_message.txt
        echo "</details>" >> format_patch_message.txt
        echo "" >> format_patch_message.txt
        echo "More details about our use of clang-format can be found in the [wiki](https://github.com/trilinos/Trilinos/wiki/Clang\%E2\%80\%90format)." >> format_patch_message.txt

    - name: Post artifact in issue comment
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
      if: ${{ hashFiles('format_patch.txt') != '' }}
      with:
        message-id: clang-format-patch
        refresh-message-position: true
        message-path: format_patch_message.txt

    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      if: ${{ hashFiles('format_patch.txt') != '' }}
      with:
        script: |
          core.setFailed('Your PR updated files that did not respect package clang formatting settings. Please download and apply the formatting patch! It is located at the bottom of the summary tab for this workflow and at this link: ${{ steps.upload-artf.outputs.artifact-url }}')
