name: MergeTestConfig1

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
    branches:
    - master
    - develop
  workflow_dispatch:

jobs:
  inteloneapi:
    runs-on: [self-hosted, trilogpu01]
    env:
      I_MPI_CC: icx
      I_MPI_CXX: icpx
      I_MPI_FC: ifx
    container:
      image: registry-ex.sandia.gov/evho/github-actions-trilinos-containers
      options: --shm-size=8g
    steps:
      - name: env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
      - name: module list
        shell: bash
        run: |
          bash -l -c "module list"
          printenv PATH
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: make dirs
        working-directory: /
        run: |
          mkdir -p /home/Trilinos/src/Trilinos
          mkdir -p /home/Trilinos/install
      - name: clone trilinos
        uses: actions/checkout@v3
        with:
          path: /__w/Trilinos/Trilinos/src/Trilinos
      - name: move trilinos
        working-directory: /__w/Trilinos/Trilinos/src/Trilinos
        run: |
          mv -f * /home/Trilinos/src/Trilinos
      - name: configure trilinos
        working-directory: /home/Trilinos/build/
        run: |
          bash -l -c "./configure.sh"
      - name: CMakeCache.txt
        if: always()
        working-directory: /home/Trilinos/build/
        run: |
          bash -l -c "cat CMakeCache.txt"
      - name: build trilinos
        working-directory: /home/Trilinos/build/
        run: bash -l -c "make -j8 && make install -j8"
      - name: ctest
        working-directory: /home/Trilinos/build/
        run: bash -l -c "ctest -j8"
