name: Per-Commit Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  DCO-signoff:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0

    - name: Search for signoff statements in commit messages
      run: |
        $GITHUB_WORKSPACE/commonTools/test/utilities/check-commit-signoffs.sh \
        origin/${{ github.event.pull_request.base.ref }} \
        ${{ github.event.pull_request.head.sha }}

  no-modifying-deprecated-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0

    - name: Search for signoff statements in commit messages
      run: |
        $GITHUB_WORKSPACE/commonTools/test/utilities/check-not-modify-legacy-packages.sh \
        origin/${{ github.event.pull_request.base.ref }} \
        ${{ github.event.pull_request.head.sha }}
