name: Per-Commit Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  DCO-signoff:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        fetch-depth: 0

    - name: Search for signoff statements in commit messages
      run: |
        $GITHUB_WORKSPACE/commonTools/test/utilities/check-commit-signoffs.sh \
        origin/${{ github.event.pull_request.base.ref }} \
        ${{ github.event.pull_request.head.sha }}
