name: Per-Commit Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  DCO-signoff:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0

    - name: Search for signoff statements in commit messages
      run: |
        $GITHUB_WORKSPACE/commonTools/test/utilities/check-commit-signoffs.sh \
        origin/${{ github.event.pull_request.base.ref }} \
        ${{ github.event.pull_request.head.sha }}
