name: Auto assign MueLu or Tpetra labelled issues to MueLu or Tpetra Projects

on:
  issues:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    name: Assign to MueLu or Tpetra Project
    runs-on: ubuntu-latest
    steps:
    - name: Add to MueLu Project
      uses: srggrs/assign-one-project-github-action@1.3.0
      if: contains(github.event.label.name, 'MueLu')
      with:
        project: 'https://github.com/trilinos/Trilinos/projects/5'
        column_name: 'Feature request'
    - name: Add to Tpetra Project
      uses: srggrs/assign-one-project-github-action@1.3.0    
      if: contains(github.event.label.name, 'Tpetra')
      with:
        project: 'https://github.com/trilinos/Trilinos/projects/2'
        column_name: 'Backlog'
